[theme]
base="dark"
primaryColor="#5A7D9A"  # A muted, neutral blue-gray for accents and buttons
backgroundColor="#121417"  # Dark, neutral gray with a slight cool tone
secondaryBackgroundColor="#1C1F23"  # A slightly lighter neutral gray for sidebars/cards
textColor="#FFFFFF"  # Keep the text pure white for clarity and readability
font="sans serif"  # Clean, minimal font style